version: 2.1
orbs:
  node: circleci/node@7.0.0
  slack: circleci/slack@3.4.2
jobs:
  build-docusaurus:
    docker:
      - image: cimg/node:20.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: v3
      - run:
          name: Build Docusaurus Site
          command: cd v3 && npm run build
      - persist_to_workspace:
          root: .
          paths:
            - v3/build
  build-code-type-checking:
    docker:
      - image: cimg/node:20.0
    steps:
      - checkout
      - run: sudo npm install -g bun
      - node/install-packages:
          pkg-manager: npm
          app-dir: v3
      - run:
          name: Create code snippets
          command: cd v3 && npm run write-code-blocks
      - persist_to_workspace:
          root: .
          paths:
            - v3/scripts/code-type-checking
  commit-to-the-backend-website-repository:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - backend-website-repo-{{ checksum "./.circleci/backend-website-cache-reference.md" }}
      # - run:
      #     name: Clone or Update Backend Website Repository
      #     command: |
      #       if [ ! -d "supertokens-backend-website/.git" ]; then
      #         git clone --depth=1 git@github.com:supertokens/supertokens-backend-website.git supertokens-backend-website
      #       else
      #         cd supertokens-backend-website
      #         git fetch origin
      #         git reset --hard origin/master
      #       fi
      - run: git clone --depth=1 git@github.com:supertokens/supertokens-backend-website.git supertokens-backend-website
      # - save_cache:
      #     paths:
      #       - supertokens-backend-website
      #     key: backend-website-repo-{{ checksum "./.circleci/backend-website-cache-reference.md" }}
      - attach_workspace:
          at: ./workspace
      - run: git config --global user.email "$EMAIL" && git config --global user.name "$NAME"
      - run: cd supertokens-backend-website && git checkout -b test-new-docs-branch
      - run:
          name: Copy Docusaurus Build to Backend Website
          command: |
            rm -rf supertokens-backend-website/app/docs/v2/*
            cp -R ./workspace/v3/build/* supertokens-backend-website/app/docs/v2
      - run:
          name: Commit and Push Changes
          command: |
            cd supertokens-backend-website
            git add --all
            git commit -m "docs changes"
            git push origin test-new-docs-branch
      # - slack/status
  run-code-type-checking:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    steps:
      - checkout
      - attach_workspace:
          at: ./workspace
      - run: cd ./workspace/v3/scripts/code-type-checking/csharp && docker build -t check-csharp .
      - run: docker run check-csharp
      # - slack/status
  code-checking-ios-only:
    macos:
      xcode: 14.1.0
    steps:
      - checkout
      - node/install-packages:
          app-dir: "~/project/v2"
      - run:
          name: Setup iOS env
          command: cd v2/src/plugins/codeTypeChecking/iosEnv/ && pod install
          no_output_timeout: 30m
      - run: nvm install 16 -y
      - run:
          no_output_timeout: 30m
          name: Run build for iOS docs
          command: nvm use 16 && cd v2 && npm run build:ios
      - slack/status
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-docusaurus
      - commit-to-the-backend-website-repository:
          requires:
            - build-docusaurus
          # filters:
          #   branches:
          #     only:
          #       - master
  code-type-checking:
    jobs:
      - build-code-type-checking
      - run-code-type-checking:
          requires:
            - build-code-type-checking
