version: 2.1
orbs:
  node: circleci/node@7.0.0
  slack: circleci/slack@3.4.2
commands:
  code-type-check:
    parameters:
      language:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: ./workspace
      - run: cd ./workspace/v3/scripts/code-type-checking/<<parameters.language>> && docker build -t code-check .
jobs:
  build-docs:
    docker:
      - image: cimg/node:20.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: v3
      - run:
          name: Build Docusaurus Site
          command: cd v3 && npm run build
      - persist_to_workspace:
          root: .
          paths:
            - v3/build
  build-code-type-checking:
    docker:
      - image: cimg/node:20.0
    steps:
      - checkout
      - run: sudo npm install -g bun
      - node/install-packages:
          pkg-manager: npm
          app-dir: v3
      - run:
          name: Create code snippets
          command: cd v3 && npm run write-code-blocks
      - persist_to_workspace:
          root: .
          paths:
            - v3/scripts/code-type-checking
  create-supertokens-backend-website-dev-tag:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - run: git clone --depth=1 git@github.com:supertokens/supertokens-backend-website.git --branch=master supertokens-backend-website
      - attach_workspace:
          at: ./workspace
      - run: git config --global user.email "$EMAIL" && git config --global user.name "$NAME"
      - run:
          name: Copy Docusaurus Build to Backend Website Folder
          command: |
            rm -rf supertokens-backend-website/app/docs/v2/*
            cp -R ./workspace/v3/build/* supertokens-backend-website/app/docs/v2
      - run:
          name: Commit and Push Changes
          command: |
            cd supertokens-backend-website
            git add --all
            git commit -m "docs changes"
            git push origin master
            ./releaseDev.sh
      - slack/status
  run-code-type-checking:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    steps:
      - code-type-check:
          language: "javascript"
      - code-type-check:
          language: "go"
      - code-type-check:
          language: "python"
      - code-type-check:
          language: "dart"
      - code-type-check:
          language: "swift"
      - code-type-check:
          language: "php"
      - code-type-check:
          language: "java"
      - code-type-check:
          language: "csharp"
      - code-type-check:
          language: "kotlin"
      - slack/status
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-docs:
          filters:
            branches:
              only:
                - master
      - create-supertokens-backend-website-dev-tag:
          context:
            - slack-notification
          requires:
            - build-docs
  code-type-checking:
    jobs:
      - build-code-type-checking:
          filters:
            branches:
              only:
                - master
      - run-code-type-checking:
          context:
            - slack-notification
          requires:
            - build-code-type-checking
