# fly.toml app configuration file generated for v3-sparkling-river-6434 on 2024-11-04T10:55:01Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'v3-sparkling-river-6434'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
