name: Lint Docs

on:
  # Need to fix mdx issues that appeared in the latest version of vale
  # pull_request:
  workflow_dispatch:
    # paths:
    #   - "docs/**"
    #   - ".vale.ini"

jobs:
  vale-lint:
    runs-on: ubuntu-latest
    container:
      image: jdkato/vale
    steps:
      - uses: actions/checkout@v4
      - run: vale --version

      - name: Run Vale Linting
        run: vale --minAlertLevel=error --config=.vale.ini ./docs
