name: Docs versioning
on:
  push: # Trigger the workflow on push events but only for the main branch
    branches: [ master ]
jobs:
  Tag-And-Release-Docs:
    runs-on: ubuntu-latest
    environment: Actions
    steps:
      - uses: actions/checkout@v2
      - uses: supertokens/supertokens-github-actions/docs/versioning@master
        with:
          GITHUB_TOKEN: ${{ secrets.VCS_TOKEN }}
